### ISSUE TITLE
Kind request to delete repo...

### ISSUE THREAD

**Issue by dandv** [CTumminaro/star-rating#1]
...since it shows up among [legit](https://github.com/PolymerLabs/star-ratings) search [results](https://github.com/cmartinezv/star-rating) for [rating widgets](https://github.com/dandv/comparisons/blob/master/star-rating-widgets.md).

**Comment by CTumminaro** [comment]
Apologies, life got a bit hectic with the second kid. I have the intention of porting this over to an ES6 module and including the SCSS files in the near future as it makes customizing a bit easier and there's no good reason this should require jQuery. I'm uploading this version as a good faith. Thanks for keeping the community clean!
